# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HinhhkwNY9YQtEh9ZfEoTEDCJPB2a6Pi

# New Section
"""



count_w = input().upper()  # переводим в верхний регистр

n1 = 'Аденин:'
n2 = 'Гуанин:'
n3 = 'Цитозин:'
n4 = 'Тимин:'

# Подсчитываем каждую букву
a_count = count_w.count('А')
g_count = count_w.count('Г')
c_count = count_w.count('Ц')
t_count = count_w.count('Т')

# Выводим в нужном порядке: гуанин, тимин, цитозин, аденин
print(n2, g_count)
print(n4, t_count)
print(n3, c_count)
print(n1, a_count)