# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HinhhkwNY9YQtEh9ZfEoTEDCJPB2a6Pi

# New Section
"""



s = "In 2010, someone paid 10k Bitcoin for two pizzas."
print(s[-9:])