# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HinhhkwNY9YQtEh9ZfEoTEDCJPB2a6Pi

# New Section
"""

for i in range(7):
  for j in range(i + 1):
    print('*', end='')
  print()