# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HinhhkwNY9YQtEh9ZfEoTEDCJPB2a6Pi

# New Section
"""

x= input()
y= input()
z= input()
print(z)
print(y)
print(x)