# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HinhhkwNY9YQtEh9ZfEoTEDCJPB2a6Pi

# New Section
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

class EnhancedVolatilityMomentumStrategy:
    def __init__(self, formation_period=60, volatility_growth_threshold=1.5,
                 min_volatility_ratio=2.0, entry_threshold=0.003):
        self.formation_period = formation_period  # Период формирования (3 месяца)
        self.volatility_growth_threshold = volatility_growth_threshold  # Рост волатильности > 50%
        self.min_volatility_ratio = min_volatility_ratio  # Минимальное отношение волатильностей
        self.entry_threshold = entry_threshold  # 0.3% для входа
        self.last_volatility_ratio = None

    def calculate_volatility(self, returns, window=20):
        """Расчет волатильности с различными окнами"""
        return returns.rolling(window=window).std() * np.sqrt(252)

    def analyze_volatility_regime(self, prices):
        """Анализ режима волатильности"""
        returns = np.log(prices / prices.shift(1))

        # Краткосрочная vs долгосрочная волатильность
        vol_short = self.calculate_volatility(returns, window=10)
        vol_long = self.calculate_volatility(returns, window=20)

        # Определение тренда волатильности
        volatility_trend = vol_short / vol_long

        return {
            'volatility_trend': volatility_trend,
            'is_volatility_growing': volatility_trend.iloc[-1] > self.volatility_growth_threshold,
            'volatility_momentum': (vol_short.iloc[-1] - vol_long.iloc[-1]) / vol_long.iloc[-1]
        }

    def prepare_trading_day(self, prices_numerator, prices_denominator):
        """Подготовка к торговому дню - этап 1"""
        returns_num = np.log(prices_numerator / prices_numerator.shift(1))
        returns_den = np.log(prices_denominator / prices_denominator.shift(1))

        # Волатильности за formation период
        vol_num = self.calculate_volatility(returns_num.tail(self.formation_period))
        vol_den = self.calculate_volatility(returns_den.tail(self.formation_period))

        # Анализ поведения
        correlation = returns_num.tail(self.formation_period).corr(returns_den.tail(self.formation_period))

        # Сохраняем последний коэффициент уравнивания
        current_vol_ratio = vol_num.iloc[-1] / vol_den.iloc[-1]
        self.last_volatility_ratio = current_vol_ratio

        # Анализ режимов волатильности
        vol_regime_num = self.analyze_volatility_regime(prices_numerator.tail(self.formation_period))
        vol_regime_den = self.analyze_volatility_regime(prices_denominator.tail(self.formation_period))

        return {
            'volatility_ratio': current_vol_ratio,
            'correlation': correlation,
            'vol_regime_num': vol_regime_num,
            'vol_regime_den': vol_regime_den,
            'passes_screening': (
                abs(correlation) > 0.7 and
                current_vol_ratio >= self.min_volatility_ratio and
                (vol_regime_num['is_volatility_growing'] or vol_regime_den['is_volatility_growing'])
            )
        }

    def execute_trading(self, prices_numerator, prices_denominator, analysis_data):
        """Этап 2 - Исполнение торговли"""
        if not analysis_data['passes_screening']:
            return None, "Не проходит скрининг"

        # Применяем последний коэффициент уравнивания
        if self.last_volatility_ratio > 1:
            # numerator более волатильный
            adjusted_denominator = prices_denominator * self.last_volatility_ratio
            adjusted_numerator = prices_numerator
            vol_priority = 'numerator'
        else:
            # denominator более волатильный
            adjusted_numerator = prices_numerator / self.last_volatility_ratio
            adjusted_denominator = prices_denominator
            vol_priority = 'denominator'

        # Анализ движения с начала дня
        today_mask = prices_numerator.index >= prices_numerator.index[-1].normalize()
        today_prices_num = adjusted_numerator[today_mask]
        today_prices_den = adjusted_denominator[today_mask]

        if len(today_prices_num) < 2:
            return None, "Недостаточно данных за сегодня"

        # Относительное движение (освобожденное от уравнивания)
        move_num = (today_prices_num.iloc[-1] / today_prices_num.iloc[0]) - 1
        move_den = (today_prices_den.iloc[-1] / today_prices_den.iloc[0]) - 1
        relative_move = move_num - move_den

        # Генерация сигнала на основе направленного движения
        signal = None
        rationale = ""

        if abs(relative_move) >= self.entry_threshold:
            if vol_priority == 'numerator':
                if relative_move > 0:
                    signal = 'BUY_NUMERATOR_SELL_DENOMINATOR'
                    rationale = f"Волатильный актив растет быстрее: +{relative_move:.3%}"
                else:
                    signal = 'SELL_NUMERATOR_BUY_DENOMINATOR'
                    rationale = f"Волатильный актив падает быстрее: {relative_move:.3%}"
            else:
                if relative_move > 0:
                    signal = 'SELL_NUMERATOR_BUY_DENOMINATOR'
                    rationale = f"Менее волатильный актив отстает: +{relative_move:.3%}"
                else:
                    signal = 'BUY_NUMERATOR_SELL_DENOMINATOR'
                    rationale = f"Менее волатильный актив устойчивее: {relative_move:.3%}"

        return signal, {
            'signal': signal,
            'relative_move': relative_move,
            'vol_priority': vol_priority,
            'volatility_ratio': analysis_data['volatility_ratio'],
            'rationale': rationale,
            'move_breakdown': {'numerator': move_num, 'denominator': move_den}
        }

# СИМУЛЯЦИЯ РЕАЛИСТИЧНОГО СЦЕНАРИЯ
def simulate_volatility_expansion_scenario():
    """Симуляция сценария расширения волатильности"""
    np.random.seed(42)
    n_days = 100
    dates = pd.date_range('2024-06-01', periods=n_days, freq='D')

    # Базовый тренд (общий для обоих активов)
    base_trend = np.cumsum(np.random.normal(0.0005, 0.005, n_days))

    # Актив A (будущий high-vol) - накопление волатильности
    volatility_regime_change = 50  # день изменения режима

    # Фоновая волатильность
    noise_A = np.random.normal(0, 0.015, n_days)
    noise_B = np.random.normal(0, 0.008, n_days)

    # Добавляем всплеск волатильности для актива A
    for i in range(volatility_regime_change, n_days):
        if i % 3 == 0:  # Импульсные движения
            noise_A[i] += np.random.normal(0, 0.03)

    prices_A = 100 * np.exp(base_trend + np.cumsum(noise_A))
    prices_B = 100 * np.exp(base_trend + np.cumsum(noise_B))

    return pd.DataFrame({'Asset_A': prices_A, 'Asset_B': prices_B}, index=dates)

# ВАЛИДАЦИЯ СТРАТЕГИИ
def validate_enhanced_strategy():
    print("🔒 УСОВЕРШЕНСТВОВАННЫЙ АНАЛИЗ СТРАТЕГИИ")
    print("=" * 65)

    # Генерируем реалистичные данные
    data = simulate_volatility_expansion_scenario()

    strategy = EnhancedVolatilityMomentumStrategy(
        formation_period=60,
        volatility_growth_threshold=1.5,
        min_volatility_ratio=2.0,
        entry_threshold=0.003
    )

    # Тестируем на последних данных
    test_prices_num = data['Asset_A']
    test_prices_den = data['Asset_B']

    # Этап 1: Подготовка
    analysis = strategy.prepare_trading_day(test_prices_num, test_prices_den)

    print("📊 РЕЗУЛЬТАТЫ СКРИНИНГА (Этап 1):")
    print(f"Отношение волатильностей: {analysis['volatility_ratio']:.2f}")
    print(f"Корреляция: {analysis['correlation']:.3f}")
    print(f"Рост волатильности Numerator: {analysis['vol_regime_num']['is_volatility_growing']}")
    print(f"Рост волатильности Denominator: {analysis['vol_regime_den']['is_volatility_growing']}")
    print(f"Проходит скрининг: {analysis['passes_screening']}")

    if analysis['passes_screening']:
        # Этап 2: Торговля
        signal, details = strategy.execute_trading(test_prices_num, test_prices_den, analysis)

        print(f"\n🎯 ТОРГОВЫЙ СИГНАЛ (Этап 2):")
        print(f"Сигнал: {signal}")
        print(f"Обоснование: {details['rationale']}")
        print(f"Относительное движение: {details['relative_move']:.3%}")
        print(f"Движение Numerator: {details['move_breakdown']['numerator']:.3%}")
        print(f"Движение Denominator: {details['move_breakdown']['denominator']:.3%}")

        # Визуализация
        plt.figure(figsize=(15, 10))

        # График 1: Исходные цены
        plt.subplot(3, 1, 1)
        plt.plot(data.index, data['Asset_A']/data['Asset_A'].iloc[0], label='Asset A (High Vol)', linewidth=2)
        plt.plot(data.index, data['Asset_B']/data['Asset_B'].iloc[0], label='Asset B (Low Vol)', linewidth=2)
        plt.title('Исходные нормализованные цены')
        plt.legend()
        plt.grid(True, alpha=0.3)

        # График 2: Освобожденные от уравнивания цены
        plt.subplot(3, 1, 2)
        if strategy.last_volatility_ratio > 1:
            adjusted_B = data['Asset_B'] * strategy.last_volatility_ratio
            plt.plot(data.index, data['Asset_A']/data['Asset_A'].iloc[0], label='Asset A (естественная)', linewidth=2)
            plt.plot(data.index, adjusted_B/adjusted_B.iloc[0], label='Asset B (освобожденный)', linewidth=2)
        else:
            adjusted_A = data['Asset_A'] / strategy.last_volatility_ratio
            plt.plot(data.index, adjusted_A/adjusted_A.iloc[0], label='Asset A (освобожденный)', linewidth=2)
            plt.plot(data.index, data['Asset_B']/data['Asset_B'].iloc[0], label='Asset B (естественная)', linewidth=2)
        plt.title('Цены после освобождения от уравнивания волатильности')
        plt.legend()
        plt.grid(True, alpha=0.3)

        # График 3: Относительное движение
        plt.subplot(3, 1, 3)
        relative_performance = (data['Asset_A']/data['Asset_A'].iloc[0]) / (data['Asset_B']/data['Asset_B'].iloc[0])
        plt.plot(data.index, relative_performance, label='Относительная производительность A/B', color='red', linewidth=2)
        plt.axhline(y=1, color='black', linestyle='--', alpha=0.5)
        plt.title('Относительная производительность (A/B)')
        plt.legend()
        plt.grid(True, alpha=0.3)

        plt.tight_layout()
        plt.show()

        return signal, details

    return None, analysis

# ЗАПУСК
if __name__ == "__main__":
    signal, details = validate_enhanced_strategy()